# Generated by Django 5.2.8 on 2026-01-18 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_banner_image_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_role', models.CharField(max_length=255)),
                ('match_percentage', models.FloatField()),
                ('missing_skills', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
