# Generated by Django 5.2.8 on 2026-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_careerprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprediction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
