# Generated by Django 6.0.1 on 2026-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprediction',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
